import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js';
import {getAuth,signInWithEmailAndPassword,onAuthStateChanged,signOut} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import {getFirestore,collection,getDocs,doc,getDoc,setDoc,addDoc,updateDoc,deleteDoc,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
import {getStorage,ref,uploadBytesResumable,getDownloadURL} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-storage.js';
import {firebaseConfig} from './firebase-config.js';
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),storage=getStorage(app);
const $=id=>document.getElementById(id),money=n=>'₹'+Number(n||0).toLocaleString('en-IN'),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let products=[],orders=[],view='dashboard',store={upiId:'',qrUrl:'',whatsapp:'',email:''};
async function adminOK(uid){const s=await getDoc(doc(db,'admins',uid));return s.exists()&&s.data().active===true}
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginError').textContent='';try{await signInWithEmailAndPassword(auth,$('email').value,$('password').value)}catch(x){$('loginError').textContent='Sign-in failed. Check credentials and Firebase configuration.'}};
$('logout').onclick=()=>signOut(auth);
onAuthStateChanged(auth,async user=>{if(!user){$('login').classList.remove('hidden');$('app').classList.add('hidden');return}try{if(!await adminOK(user.uid))throw new Error('not-admin');$('login').classList.add('hidden');$('app').classList.remove('hidden');$('adminEmail').textContent=user.email;await load();render()}catch(e){await signOut(auth);$('loginError').textContent='This account is not an active Mirella admin.'}});
async function load(){const[p,o,s]=await Promise.all([getDocs(collection(db,'products')),getDocs(collection(db,'orders')),getDoc(doc(db,'settings','store'))]);products=p.docs.map(d=>({id:d.id,...d.data()}));orders=o.docs.map(d=>({id:d.id,...d.data()}));store=s.exists()?{...store,...s.data()}:store;}
function render(){const titles={dashboard:'Dashboard',orders:'Orders',products:'Products',settings:'Store Settings'};$('title').textContent=titles[view];document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===view));({dashboard:dashboard,orders:ordersPage,products:productsPage,settings:settingsPage})[view]()}
document.querySelectorAll('[data-view]').forEach(x=>x.onclick=()=>{view=x.dataset.view;render()});
function revenue(){return orders.filter(o=>o.paymentStatus==='paid'||o.paymentMethod==='cod').reduce((a,o)=>a+Number(o.total||0),0)}
function dashboard(){const pending=orders.filter(o=>!['delivered','cancelled'].includes(o.status)).length;const paid=orders.filter(o=>o.paymentStatus==='paid').length;$('content').innerHTML=`<div class="grid"><div class="kpi"><span>Total revenue</span><strong>${money(revenue())}</strong></div><div class="kpi"><span>Total orders</span><strong>${orders.length}</strong></div><div class="kpi"><span>Active products</span><strong>${products.filter(p=>p.active!==false).length}</strong></div><div class="kpi"><span>Pending orders</span><strong>${pending}</strong></div></div><div class="panel"><h2>Store snapshot</h2><div class="grid"><div class="kpi"><span>Paid UPI</span><strong>${paid}</strong></div><div class="kpi"><span>COD orders</span><strong>${orders.filter(o=>o.paymentMethod==='cod').length}</strong></div><div class="kpi"><span>Low stock</span><strong>${products.filter(p=>Number(p.stock||0)>0&&Number(p.stock||0)<=5).length}</strong></div><div class="kpi"><span>Out of stock</span><strong>${products.filter(p=>Number(p.stock||0)<=0).length}</strong></div></div></div><div class="panel"><h2>Recent orders</h2>${orderTable(orders.slice().sort(dateSort).slice(0,8))}</div>`;bindOrderChanges()}
const dateSort=(a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0);
function orderTable(arr){if(!arr.length)return'<div class="empty">No orders yet.</div>';return`<table class="table"><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Payment</th><th>Proof</th><th>Order status</th><th>Payment status</th></tr></thead><tbody>${arr.map(o=>`<tr><td><b>${esc(o.orderNumber||o.id.slice(0,8).toUpperCase())}</b></td><td>${esc(o.customer?.name)}<br><span class="muted">${esc(o.customer?.phone)}</span></td><td>${money(o.total)}</td><td>${esc(o.paymentMethod||'—')}<br><span class="muted">${esc(o.upiId||'')}</span></td><td>${o.paymentProofUrl?`<a class="btn alt" href="${esc(o.paymentProofUrl)}" target="_blank" rel="noopener">View screenshot</a>`:'—'}</td><td><select data-status="${o.id}"><option value="new" ${o.status==='new'?'selected':''}>New</option><option value="confirmed" ${o.status==='confirmed'?'selected':''}>Confirmed</option><option value="processing" ${o.status==='processing'?'selected':''}>Processing</option><option value="packed" ${o.status==='packed'?'selected':''}>Packed</option><option value="shipped" ${o.status==='shipped'?'selected':''}>Shipped</option><option value="delivered" ${o.status==='delivered'?'selected':''}>Delivered</option><option value="cancelled" ${o.status==='cancelled'?'selected':''}>Cancelled</option></select></td><td><select data-payment="${o.id}"><option value="pending" ${o.paymentStatus==='pending'?'selected':''}>Pending verification</option><option value="paid" ${o.paymentStatus==='paid'?'selected':''}>Paid</option><option value="failed" ${o.paymentStatus==='failed'?'selected':''}>Failed</option><option value="refunded" ${o.paymentStatus==='refunded'?'selected':''}>Refunded</option></select></td></tr>`).join('')}</tbody></table>`}
function bindOrderChanges(){document.querySelectorAll('[data-status]').forEach(s=>s.onchange=async()=>{await updateDoc(doc(db,'orders',s.dataset.status),{status:s.value,updatedAt:serverTimestamp()});await load();render()});document.querySelectorAll('[data-payment]').forEach(s=>s.onchange=async()=>{await updateDoc(doc(db,'orders',s.dataset.payment),{paymentStatus:s.value,updatedAt:serverTimestamp()});await load();render()})}
function ordersPage(){orders.sort(dateSort);$('content').innerHTML=`<div class="panel"><div class="toolbar"><input id="orderSearch" placeholder="Search order, customer or phone"><select id="orderFilter"><option value="all">All statuses</option><option>new</option><option>confirmed</option><option>processing</option><option>packed</option><option>shipped</option><option>delivered</option><option>cancelled</option></select></div><div id="orderTable">${orderTable(orders)}</div></div>`;const filter=()=>{const q=$('orderSearch').value.toLowerCase(),s=$('orderFilter').value;const a=orders.filter(o=>(s==='all'||o.status===s)&&(`${o.id} ${o.orderNumber||''} ${o.customer?.name||''} ${o.customer?.phone||''}`.toLowerCase().includes(q)));$('orderTable').innerHTML=orderTable(a);bindOrderChanges()};$('orderSearch').oninput=filter;$('orderFilter').onchange=filter;bindOrderChanges()}
function productsPage(){products.sort((a,b)=>String(a.name).localeCompare(String(b.name)));$('content').innerHTML=`<div class="panel"><div class="toolbar"><button class="btn" id="addProduct">+ Add product</button><input id="productSearch" placeholder="Search products"></div><div id="productTable"></div></div>`;$('addProduct').onclick=()=>openProduct();$('productSearch').oninput=renderProductRows;renderProductRows()}
function renderProductRows(){const q=$('productSearch').value.toLowerCase(),a=products.filter(p=>String(p.name).toLowerCase().includes(q));$('productTable').innerHTML=a.length?`<table class="table"><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>State</th><th>Actions</th></tr></thead><tbody>${a.map(p=>`<tr><td>${p.imageUrl?`<img class="product-thumb" src="${esc(p.imageUrl)}">`:''}<br><b>${esc(p.name)}</b></td><td>${esc(p.category)}</td><td>${money(p.price)}</td><td>${p.stock??0}</td><td><span class="pill">${p.active!==false?'Active':'Hidden'}</span></td><td><button class="btn alt" data-edit="${p.id}">Edit</button> <button class="btn danger" data-delete="${p.id}">Delete</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty">No products.</div>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openProduct(b.dataset.edit));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>removeProduct(b.dataset.delete))}
function openProduct(id){const p=products.find(x=>x.id===id);$('productId').value=p?.id||'';$('pName').value=p?.name||'';$('pCategory').value=p?.category||'skin';$('pPrice').value=p?.price??'';$('pStock').value=p?.stock??0;$('pImage').value=p?.imageUrl||'';$('pDescription').value=p?.description||'';$('pActive').checked=p?.active!==false;$('pFile').value='';$('uploadProgress').style.width='0';$('modalTitle').textContent=p?'Edit product':'New product';$('productModal').classList.add('open')}
$('closeModal').onclick=()=>$('productModal').classList.remove('open');
async function uploadImage(file){if(!file)return $('pImage').value.trim();if(file.size>5*1024*1024)throw new Error('Image must be 5 MB or smaller.');const storageRef=ref(storage,`products/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`);return new Promise((resolve,reject)=>{const task=uploadBytesResumable(storageRef,file);task.on('state_changed',s=>$('uploadProgress').style.width=((s.bytesTransferred/s.totalBytes)*100)+'%',reject,async()=>resolve(await getDownloadURL(task.snapshot.ref)))})}
$('productForm').onsubmit=async e=>{e.preventDefault();const id=$('productId').value;const button=e.submitter;button.disabled=true;button.textContent='Saving…';try{const imageUrl=await uploadImage($('pFile').files[0]);const data={name:$('pName').value.trim(),category:$('pCategory').value,price:Number($('pPrice').value),stock:Number($('pStock').value),imageUrl,description:$('pDescription').value.trim(),active:$('pActive').checked,updatedAt:serverTimestamp()};if(id)await updateDoc(doc(db,'products',id),data);else await addDoc(collection(db,'products'),{...data,createdAt:serverTimestamp()});$('productModal').classList.remove('open');await load();render()}catch(err){alert(err.message||'Unable to save product.')}finally{button.disabled=false;button.textContent='Save product'}};
async function removeProduct(id){if(!confirm('Delete this product?'))return;await deleteDoc(doc(db,'products',id));await load();render()}
async function uploadQr(file){if(!file)return store.qrUrl||'';if(!file.type.startsWith('image/'))throw new Error('QR code must be an image.');if(file.size>5*1024*1024)throw new Error('QR image must be 5 MB or smaller.');const r=ref(storage,`store/upi-qr-${Date.now()}`);const task=uploadBytesResumable(r,file,{contentType:file.type});return new Promise((resolve,reject)=>task.on('state_changed',null,reject,async()=>resolve(await getDownloadURL(task.snapshot.ref))))}
function settingsPage(){$('content').innerHTML=`<div class="panel"><h2>UPI & payment settings</h2><p class="muted">Customers can pay by scanning your QR or opening a UPI app. These settings are shown on checkout, so keep the UPI ID accurate.</p><form id="settingsForm" class="form"><label>Mirella Glow UPI ID<input id="sUpi" value="${esc(store.upiId)}" placeholder="mirellaglow@upi" required></label><label>UPI QR code image<input id="sQrFile" type="file" accept="image/*"></label>${store.qrUrl?`<img src="${esc(store.qrUrl)}" alt="Current UPI QR" style="width:220px;max-width:100%;aspect-ratio:1;object-fit:contain;border:1px solid #e5d9d1;border-radius:14px;padding:8px;background:#fff">`:''}<label>QR image URL<input id="sQr" value="${esc(store.qrUrl)}" placeholder="Upload a QR above or paste its URL"></label><label>WhatsApp number<input id="sWhatsApp" value="${esc(store.whatsapp)}" placeholder="919876543210"></label><label>Support email<input id="sEmail" type="email" value="${esc(store.email)}" placeholder="hello@example.com"></label><button class="btn" id="saveSettings">Save store settings</button><div id="settingsMsg" class="muted"></div></form></div><div class="panel"><h2>Admin access</h2><div class="notice">Your Firebase Auth account is allowed into this studio only when <b>admins/${esc(auth.currentUser.uid)}</b> exists in Firestore with <b>active: true</b>.</div></div>`;$('settingsForm').onsubmit=async e=>{e.preventDefault();const b=$('saveSettings');b.disabled=true;b.textContent='Saving…';try{let qr=$('sQr').value.trim();if($('sQrFile').files[0])qr=await uploadQr($('sQrFile').files[0]);store={upiId:$('sUpi').value.trim(),qrUrl:qr,whatsapp:$('sWhatsApp').value.trim(),email:$('sEmail').value.trim()};await setDoc(doc(db,'settings','store'),{...store,updatedAt:serverTimestamp()},{merge:true});$('settingsMsg').textContent='Saved successfully. The storefront will use these payment settings now.'}catch(err){$('settingsMsg').textContent=err.message||'Could not save settings.'}finally{b.disabled=false;b.textContent='Save store settings'}}}
