import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js';
import { getFirestore, collection, getDocs, addDoc, doc, getDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
import { getStorage, ref, uploadBytes, getDownloadURL } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-storage.js';
import { firebaseConfig } from './firebase-config.js';

const app=initializeApp(firebaseConfig),db=getFirestore(app),storage=getStorage(app);
const $=id=>document.getElementById(id); const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let products=[],cart=JSON.parse(localStorage.getItem('mirella-cart')||'[]'),category='all',store={upiId:'',qrUrl:'',whatsapp:'',email:''};
const save=()=>{localStorage.setItem('mirella-cart',JSON.stringify(cart));renderCartCount();};
const toast=m=>{const t=$('toast');if(!t)return alert(m);t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)};
async function loadStore(){try{const s=await getDoc(doc(db,'settings','store'));if(s.exists())store={...store,...s.data()}}catch(e){console.warn('Store settings unavailable',e)};injectPaymentUI();}
async function loadProducts(){try{const snap=await getDocs(collection(db,'products'));products=snap.docs.map(d=>({id:d.id,...d.data()})).filter(p=>p.active!==false);renderProducts()}catch(e){$('products').innerHTML='<div class="empty">The collection is temporarily unavailable. Please try again shortly.</div>';console.error(e)}}
function renderProducts(){const list=category==='all'?products:products.filter(p=>String(p.category||'').toLowerCase()===category);$('products').innerHTML=list.length?list.map(p=>`<article class="product"><div class="product-img">${p.imageUrl?`<img src="${esc(p.imageUrl)}" alt="${esc(p.name)}" loading="lazy">`:`<span>${esc(p.name||'Mirella')}</span>`}</div><div class="product-body"><span class="tag">${esc(p.category||'beauty')}</span><h3>${esc(p.name)}</h3><div class="desc">${esc(p.description||'A beautiful addition to your daily ritual.')}</div><div class="price-row"><strong>${money(p.price)}</strong><button class="add ${Number(p.stock||0)<=0?'sold':''}" data-add="${p.id}" ${Number(p.stock||0)<=0?'disabled':''}>${Number(p.stock||0)<=0?'—':'+'}</button></div></div></article>`).join(''):'<div class="empty">No products in this collection yet.</div>';document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addToCart(b.dataset.add));}
function addToCart(id){const p=products.find(x=>x.id===id);if(!p)return;const max=Math.max(0,Number(p.stock||0)),item=cart.find(x=>x.id===id);if(max<1)return toast('This product is currently out of stock.');if(item){if(item.qty>=max)return toast('You have reached the available stock.');item.qty++}else cart.push({id:p.id,name:p.name,price:Number(p.price||0),imageUrl:p.imageUrl||'',qty:1});save();toast('Added to your bag');}
function renderCartCount(){$('cartCount').textContent=cart.reduce((a,x)=>a+x.qty,0)}
function renderCart(){if(!cart.length){$('cartItems').innerHTML='<div class="empty">Your bag is waiting for something beautiful.</div>';$('cartSummary').innerHTML='';return}let total=0;$('cartItems').innerHTML=cart.map(x=>{total+=x.price*x.qty;return `<div class="cart-item"><div><b>${esc(x.name)}</b><div class="cart-meta">${money(x.price)} each</div></div><div class="qty"><button data-dec="${x.id}">−</button><span>${x.qty}</span><button data-inc="${x.id}">+</button></div></div>`}).join('');$('cartSummary').innerHTML=`<div class="total"><span>Total</span><span>${money(total)}</span></div><button class="btn primary" id="checkoutBtn" style="width:100%">Proceed to checkout</button>`;document.querySelectorAll('[data-inc]').forEach(b=>b.onclick=()=>changeQty(b.dataset.inc,1));document.querySelectorAll('[data-dec]').forEach(b=>b.onclick=()=>changeQty(b.dataset.dec,-1));$('checkoutBtn').onclick=()=>{$('cartDrawer').classList.remove('open');$('checkoutModal').classList.add('open');injectPaymentUI();};}
function changeQty(id,delta){const i=cart.find(x=>x.id===id);if(!i)return;i.qty+=delta;if(i.qty<=0)cart=cart.filter(x=>x.id!==id);else{const p=products.find(x=>x.id===id);if(p&&i.qty>Number(p.stock||0))i.qty=Number(p.stock||0)}save();renderCart();}
function total(){return cart.reduce((a,x)=>a+x.price*x.qty,0)}
function buildUpiLink(kind='upi'){const amount=(total()+(total()>=999?0:99)).toFixed(2),pa=encodeURIComponent(store.upiId||''),pn=encodeURIComponent('Mirella Glow'),base=`pa=${pa}&pn=${pn}&am=${amount}&cu=INR`;return kind==='gpay'?`tez://upi/pay?${base}`:kind==='phonepe'?`phonepe://pay?${base}`:`upi://pay?${base}`;}
function injectPaymentUI(){const form=$('checkoutForm');if(!form)return;let box=$('paymentBox');if(!box){box=document.createElement('div');box.id='paymentBox';const submit=form.querySelector('button[type="submit"]');form.insertBefore(box,submit||null);}const online=!!store.upiId;box.innerHTML=`<label>Payment method<select id="cPayment"><option value="cod">Cash on delivery</option>${online?'<option value="upi">UPI — Pay now</option>':''}</select></label><div id="upiPanel" style="display:none;margin-top:4px"><div class="notice"><b>Pay ₹${money(total()+(total()>=999?0:99)).replace('₹','₹')}</b> to <b>${esc(store.upiId||'UPI ID not configured')}</b>.<br>Scan the QR or use a UPI app. After payment, attach the payment screenshot below.</div>${store.qrUrl?`<img src="${esc(store.qrUrl)}" alt="Mirella Glow UPI QR" style="display:block;width:min(260px,100%);aspect-ratio:1;object-fit:contain;margin:14px auto;border:1px solid #eadfd8;border-radius:14px;background:#fff">`:''}<div style="display:flex;gap:8px;flex-wrap:wrap;margin:10px 0"><a class="btn primary" id="upiOpen" href="${buildUpiLink()}">Open UPI app</a><a class="btn" href="${buildUpiLink('gpay')}">Google Pay</a><a class="btn" href="${buildUpiLink('phonepe')}">PhonePe</a></div><label>Payment screenshot <input id="paymentScreenshot" type="file" accept="image/*"></label><div class="muted" style="margin-top:5px">Required for UPI orders. Your screenshot is attached to the order for verification.</div></div>`;const select=$('cPayment');select.onchange=()=>{$('upiPanel').style.display=select.value==='upi'?'block':'none'};}
async function uploadPaymentProof(file){if(!file)throw new Error('Please attach your UPI payment screenshot.');if(!file.type.startsWith('image/'))throw new Error('Payment proof must be an image.');if(file.size>5*1024*1024)throw new Error('Payment screenshot must be 5 MB or smaller.');const path=`payment-proofs/${Date.now()}-${crypto.randomUUID()}.${(file.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'')}`;const r=ref(storage,path);await uploadBytes(r,file,{contentType:file.type});return getDownloadURL(r)}
async function createOrder(customer,paymentMethod,paymentProofUrl=''){const refNo=`MG-${Date.now()}-${Math.random().toString(36).slice(2,7).toUpperCase()}`,sub=total(),shipping=sub>=999?0:99;const order={orderNumber:refNo,customer,items:cart.map(x=>({productId:x.id,name:x.name,price:x.price,qty:x.qty,imageUrl:x.imageUrl||''})),subtotal:sub,shipping,total:sub+shipping,status:'new',paymentStatus:'pending',paymentMethod,paymentProofUrl,upiId:paymentMethod==='upi'?store.upiId:'',createdAt:serverTimestamp(),updatedAt:serverTimestamp()};const snap=await addDoc(collection(db,'orders'),order);return {id:snap.id,...order}}
$('checkoutForm').onsubmit=async e=>{e.preventDefault();if(!cart.length)return toast('Your bag is empty.');const button=e.submitter;button.disabled=true;button.textContent='Processing…';const customer={name:$('cName').value.trim(),phone:$('cPhone').value.trim(),email:$('cEmail')?.value.trim()||'',address:$('cAddress').value.trim(),city:$('cCity').value.trim(),state:$('cState').value.trim(),pincode:$('cPincode').value.trim()};const payment=$('cPayment')?.value||'cod';try{let proof='';if(payment==='upi'){if(!store.upiId)throw new Error('UPI payment is not configured yet. Please choose COD.');proof=await uploadPaymentProof($('paymentScreenshot')?.files[0]);}const order=await createOrder(customer,payment,proof);cart=[];save();$('checkoutForm').style.display='none';$('checkoutResult').innerHTML=`<div class="success"><div class="eyebrow">Order received</div><div class="order-number">${esc(order.orderNumber)}</div><p>${payment==='upi'?'Your payment screenshot has been attached for verification.':'Your COD order has been recorded successfully.'} We will contact you with updates.</p><button class="btn primary" onclick="location.reload()">Continue shopping</button></div>`;renderCart()}catch(err){console.error(err);toast(err.message||'Could not place the order. Please try again.')}finally{button.disabled=false;button.textContent='Place order'}};
$('cartBtn').onclick=()=>{$('cartDrawer').classList.add('open');renderCart()};$('closeCart').onclick=()=>$('cartDrawer').classList.remove('open');$('closeCheckout').onclick=()=>$('checkoutModal').classList.remove('open');$('menuBtn').onclick=()=>document.querySelector('.links').classList.toggle('mobile-open');$('searchBtn').onclick=()=>{const q=prompt('Search products');if(q){const found=products.filter(p=>String(p.name).toLowerCase().includes(q.toLowerCase()));$('products').innerHTML=found.length?found.map(p=>`<article class="product"><div class="product-img">${p.imageUrl?`<img src="${esc(p.imageUrl)}" alt="${esc(p.name)}">`:''}</div><div class="product-body"><span class="tag">${esc(p.category||'beauty')}</span><h3>${esc(p.name)}</h3><div class="desc">${esc(p.description||'')}</div><div class="price-row"><strong>${money(p.price)}</strong><button class="add" data-add="${p.id}">+</button></div></div></article>`).join(''):'<div class="empty">No matching products.</div>';document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addToCart(b.dataset.add));}};
document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{category=b.dataset.cat;document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x===b));renderProducts()});$('year').textContent=new Date().getFullYear();$('whatsappLink').href=store.whatsapp?'https://wa.me/'+String(store.whatsapp).replace(/\D/g,'')+'?text='+encodeURIComponent('Hello Mirella Glow, I need help with an order.'):'https://wa.me/?text='+encodeURIComponent('Hello Mirella Glow, I need help with an order.');renderCartCount();loadStore();loadProducts();
