import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js';
import {getFirestore,collection,getDocs,addDoc,doc,getDoc,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
import {getStorage,ref,uploadBytes,getDownloadURL} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-storage.js';
import {firebaseConfig} from './firebase-config.js';
const app=initializeApp(firebaseConfig),db=getFirestore(app),storage=getStorage(app);
const $=id=>document.getElementById(id),money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const text=v=>Array.isArray(v)?v.join(' '):String(v??'');
let products=[],cart=JSON.parse(localStorage.getItem('mirella-cart')||'[]'),category='all';
let store={upiId:'',qrUrl:'',whatsapp:'',email:'',logoUrl:'',banners:[],videos:[],announcementSlides:[]};
const save=()=>{localStorage.setItem('mirella-cart',JSON.stringify(cart));renderCartCount()};
const toast=m=>{const t=$('toast');if(!t)return alert(m);t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)};
async function loadStore(){try{const s=await getDoc(doc(db,'settings','store'));if(s.exists())store={...store,...s.data()}}catch(e){console.warn(e)}applyBranding();renderPosterCarousel();renderVideos();}
function applyBranding(){const logo=$('logoImg');if(logo&&store.logoUrl){logo.src=store.logoUrl;logo.style.display='block'}const wa=String(store.whatsapp||'').replace(/\D/g,'');if($('whatsappLink'))$('whatsappLink').href=wa?`https://wa.me/${wa}?text=${encodeURIComponent('Hello Mirella Glow, I need help with an order.')}`:'#';if($('emailLink')&&store.email)$('emailLink').href='mailto:'+store.email;}
function renderAnnouncements(){const slides=(Array.isArray(store.announcementSlides)?store.announcementSlides:[]).filter(Boolean);const track=$('announcementTrack');if(!track)return;const data=slides.length?slides:['Free shipping on orders above ₹999','New beauty drops, curated for your glow','Easy UPI checkout + payment proof'];track.innerHTML=data.map(x=>`<span>${esc(typeof x==='string'?x:x.text||'')}</span>`).join('');if(data.length>1){let i=0;setInterval(()=>{i=(i+1)%data.length;track.style.transform=`translateX(-${i*100}%)`},3500)}}
function renderPosterCarousel(){const area=$('posterShowcase');if(!area)return;const posters=Array.isArray(store.banners)?store.banners.filter(x=>x&&x.imageUrl):[];if(!posters.length){area.innerHTML='<div class="poster-track"><div class="poster-card"><div class="poster-copy"><span>Mirella Glow</span><h3>Curated beauty for your everyday ritual.</h3><p>Promotional posters will appear here when added from the admin studio.</p></div></div></div>';return}area.innerHTML=`<div class="poster-track" id="posterTrack">${posters.map(p=>`<article class="poster-card"><img src="${esc(p.imageUrl)}" alt="${esc(p.title||'Mirella Glow promotion')}" loading="lazy"><div class="poster-copy"><span>${esc(p.eyebrow||'Mirella Glow')}</span><h3>${esc(p.title||'Beauty, refined.')}</h3>${p.subtitle?`<p>${esc(p.subtitle)}</p>`:''}${p.buttonText?`<a class="hero-cta" style="background:#fff;color:#211816;border-color:#fff;padding:10px 17px" href="${esc(p.buttonLink||'#shop')}">${esc(p.buttonText)}</a>`:''}</div></article>`).join('')}</div>`;const track=$('posterTrack');if(posters.length>1){let i=0;setInterval(()=>{i=(i+1)%posters.length;const card=track.children[i];if(card)track.scrollTo({left:card.offsetLeft-beautyOffset(track),behavior:'smooth'})},6000)}}
function beautyOffset(el){return Math.max(0,(el.parentElement?.getBoundingClientRect().left||0)-(el.getBoundingClientRect().left||0))}
function renderVideos(){const area=$('videoShowcase'),rail=$('videoRail');const videos=Array.isArray(store.videos)?store.videos.filter(v=>v&&v.videoUrl):[];if(!area||!rail)return;if(!videos.length){area.style.display='none';return}area.style.display='block';rail.innerHTML=videos.map(v=>`<article class="video-card"><video src="${esc(v.videoUrl)}" ${v.posterUrl?`poster="${esc(v.posterUrl)}"`:''} muted autoplay loop playsinline preload="metadata" disablepictureinpicture controlslist="nodownload noplaybackrate nofullscreen"></video><div><span>${esc(v.tag||'Mirella Glow')}</span><h3>${esc(v.title||'A little glow, a lot of feeling.')}</h3>${v.subtitle?`<p>${esc(v.subtitle)}</p>`:''}</div></article>`).join('');rail.querySelectorAll('video').forEach(video=>{video.muted=true;video.loop=true;video.autoplay=true;video.controls=false;const play=()=>video.play().catch(()=>{});play();if('IntersectionObserver'in window){new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting?play():video.pause()),{threshold:.25}).observe(video)}})}
function valuesFor(p){return [p.name,p.category,p.description,p.badge,p.brand,p.concern,p.concerns,p.skinType,p.skinTypes,p.hairType,p.hairTypes,p.ingredients,p.ingredient,p.benefits,p.tags,p.result,p.results].map(text).join(' ').toLowerCase()}
function hasTerm(p,term){return valuesFor(p).includes(term.toLowerCase())}
function discoveryCard(label,term,count){return `<a class="discovery-card" href="#shop" data-discover="${esc(term)}"><small>${esc(label)}</small><b>${esc(term)}</b><span>${count?`${count} matching products`:'Explore the edit'}</span></a>`}
function renderDiscovery(){const concerns=['Acne & Breakouts','Pigmentation','Dark Spots','Dry Skin','Dehydration','Dullness','Sensitivity','Redness','Oil Control','Pores','Hair Fall','Frizz','Damage','Dandruff'];const results=['Glow','Hydration','Brightening','Barrier Care','Smooth Skin','Clear Skin','Hair Repair','Frizz Control','Scalp Care'];const ingredients=['Niacinamide','Vitamin C','Hyaluronic Acid','Retinol','Centella','Rice','Ceramides','Salicylic Acid'];const render=(id,label,list)=>{const el=$(id);if(!el)return;el.innerHTML=list.map(x=>discoveryCard(label,x,products.filter(p=>hasTerm(p,x)).length)).join('');el.querySelectorAll('[data-discover]').forEach(a=>a.onclick=e=>{e.preventDefault();const term=a.dataset.discover.toLowerCase();const found=products.filter(p=>hasTerm(p,term));renderProductList(found);document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));document.querySelector('#shop')?.scrollIntoView({behavior:'smooth'});})};render('concernGrid','Concern',concerns);render('resultGrid','Result',results);render('ingredientGrid','Ingredient',ingredients)}
function productCard(p){const stock=Number(p.stock||0);const compare=Number(p.compareAtPrice||p.comparePrice||0);const discount=compare>Number(p.price||0)?Math.round((1-Number(p.price||0)/compare)*100):0;return `<article class="product-card"><div class="product-media" onclick="location.href='product.html?id=${encodeURIComponent(p.id)}'" role="link" tabindex="0" onkeydown="if(event.key==='Enter')location.href='product.html?id=${encodeURIComponent(p.id)}'"><img src="${esc(p.imageUrl||'')}" alt="${esc(p.name)}" loading="lazy"><span class="product-badge">${stock>0?(p.badge||(p.newArrival?'New':p.bestseller?'Bestseller':'Curated')):'Sold out'}</span><button class="wishlist" aria-label="Save ${esc(p.name)}" onclick="event.stopPropagation()">♡</button><button class="quick-add" data-add="${p.id}" onclick="event.stopPropagation()" ${stock<=0?'disabled':''}>${stock<=0?'Sold out':'Add to bag'}</button></div><div class="product-info" onclick="location.href='product.html?id=${encodeURIComponent(p.id)}'" style="cursor:pointer"><div class="product-kicker">${esc(p.category||'Beauty')}</div><h3>${esc(p.name)}</h3><p>${esc(p.description||'A beautiful addition to your daily ritual.')}</p><div class="product-bottom"><strong>${money(p.price)}${compare>Number(p.price||0)?` <del style="font-size:10px;color:#a99">${money(compare)}</del>`:''}</strong><span>${discount?`${discount}% off`:stock>0?'In stock':'Unavailable'}</span></div></div></article>`}
function bindAdds(){document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addToCart(b.dataset.add))}
function renderProductList(list){$('products').innerHTML=list.length?list.map(productCard).join(''):'<div class="empty">No matching products in this edit.</div>';bindAdds()}
function renderProducts(){const list=category==='all'?products:products.filter(p=>String(p.category||'').toLowerCase()===category);renderProductList(list);renderMerchandising()}
function renderMerchandising(){const newest=[...products].filter(p=>p.newArrival===true||p.new===true||String(p.badge||'').toLowerCase().includes('new')).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));const best=[...products].filter(p=>p.bestseller===true||p.bestSeller===true||String(p.badge||'').toLowerCase().includes('best'));const fallbackNew=[...products].sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)).slice(0,8);const renderRail=(id,list)=>{const el=$(id);if(!el)return;const data=list.length?list:fallbackNew;el.innerHTML=data.length?data.map(productCard).join(''):'<div class="empty">No products configured for this edit yet.</div>';};renderRail('newProducts',newest);renderRail('bestProducts',best);bindAdds();renderDiscovery()}
async function loadProducts(){try{const snap=await getDocs(collection(db,'products'));products=snap.docs.map(d=>({id:d.id,...d.data()})).filter(p=>p.active!==false);renderProducts()}catch(e){console.error(e);if($('products'))$('products').innerHTML='<div class="empty">The collection is temporarily unavailable.</div>'}}
function addToCart(id){const p=products.find(x=>x.id===id);if(!p)return;const max=Number(p.stock||0),item=cart.find(x=>x.id===id);if(max<1)return toast('This product is currently sold out.');if(item){if(item.qty>=max)return toast('Available stock limit reached.');item.qty++}else cart.push({id:p.id,name:p.name,price:Number(p.price||0),imageUrl:p.imageUrl||'',qty:1});save();toast('Added to your bag')}
function renderCartCount(){$('cartCount').textContent=cart.reduce((a,x)=>a+x.qty,0)}
function renderCart(){if(!cart.length){$('cartItems').innerHTML='<div class="empty">Your bag is waiting for something beautiful.</div>';$('cartSummary').innerHTML='';return}let total=0;$('cartItems').innerHTML=cart.map(x=>{total+=x.price*x.qty;return `<div class="cart-item"><div><b>${esc(x.name)}</b><small>${money(x.price)} each</small></div><div class="qty"><button data-dec="${x.id}">−</button><span>${x.qty}</span><button data-inc="${x.id}">+</button></div></div>`}).join('');$('cartSummary').innerHTML=`<div class="cart-total"><span>Total</span><strong>${money(total)}</strong></div><button class="hero-cta full" id="checkoutBtn">Proceed to checkout</button>`;document.querySelectorAll('[data-inc]').forEach(b=>b.onclick=()=>changeQty(b.dataset.inc,1));document.querySelectorAll('[data-dec]').forEach(b=>b.onclick=()=>changeQty(b.dataset.dec,-1));$('checkoutBtn').onclick=()=>{$('cartDrawer').classList.remove('open');$('checkoutModal').classList.add('open');injectPaymentUI()}}
function changeQty(id,delta){const i=cart.find(x=>x.id===id);if(!i)return;i.qty+=delta;if(i.qty<=0)cart=cart.filter(x=>x.id!==id);else{const p=products.find(x=>x.id===id);if(p)i.qty=Math.min(i.qty,Number(p.stock||0))}save();renderCart()}
function total(){return cart.reduce((a,x)=>a+x.price*x.qty,0)}function grandTotal(){const sub=total();return sub+(sub>=999?0:99)}
function buildUpiLink(kind='upi'){const base=`pa=${encodeURIComponent(store.upiId||'')}&pn=${encodeURIComponent('Mirella Glow')}&am=${grandTotal().toFixed(2)}&cu=INR`;return kind==='gpay'?`tez://upi/pay?${base}`:kind==='phonepe'?`phonepe://pay?${base}`:`upi://pay?${base}`}
function injectPaymentUI(){const form=$('checkoutForm');if(!form)return;const box=$('paymentBox');box.innerHTML=`<label>Payment method<select id="cPayment"><option value="cod">Cash on delivery</option>${store.upiId?'<option value="upi">UPI — Pay now</option>':''}</select></label><div id="upiPanel" class="upi-panel" style="display:none"><div class="payment-summary"><span>Amount to pay</span><strong>${money(grandTotal())}</strong></div><p>Pay exactly this amount to <b>${esc(store.upiId||'UPI not configured')}</b>.</p>${store.qrUrl?`<img class="qr" src="${esc(store.qrUrl)}" alt="Mirella Glow UPI QR">`:''}<div class="pay-actions"><a class="pay-btn" href="${buildUpiLink()}">Open UPI</a><a class="pay-btn" href="${buildUpiLink('gpay')}">Google Pay</a><a class="pay-btn" href="${buildUpiLink('phonepe')}">PhonePe</a></div><label>Payment screenshot<input id="paymentScreenshot" type="file" accept="image/*"></label><small>Upload the successful payment screenshot so the Mirella team can verify your payment.</small></div>`;const select=$('cPayment');select.onchange=()=>{$('upiPanel').style.display=select.value==='upi'?'block':'none';const f=$('paymentScreenshot');if(f)f.required=select.value==='upi'};}
async function uploadPaymentProof(file){if(!file)throw new Error('Please attach your UPI payment screenshot.');if(!file.type.startsWith('image/'))throw new Error('Payment proof must be an image.');if(file.size>5*1024*1024)throw new Error('Payment screenshot must be 5 MB or smaller.');const r=ref(storage,`payment-proofs/${Date.now()}-${file.name.replace(/[^a-z0-9._-]/gi,'-')}`);await uploadBytes(r,file,{contentType:file.type});return getDownloadURL(r)}
async function createOrder(customer,paymentMethod,paymentProofUrl=''){const sub=total(),shipping=sub>=999?0:99,orderNumber=`MG-${Date.now()}-${Math.random().toString(36).slice(2,7).toUpperCase()}`;const order={orderNumber,customer,items:cart.map(x=>({productId:x.id,name:x.name,price:x.price,qty:x.qty,imageUrl:x.imageUrl||''})),subtotal:sub,shipping,total:sub+shipping,status:'new',paymentStatus:'pending',paymentMethod,paymentProofUrl,upiId:paymentMethod==='upi'?store.upiId:'',createdAt:serverTimestamp(),updatedAt:serverTimestamp()};const snap=await addDoc(collection(db,'orders'),order);return{...order,id:snap.id}}
$('checkoutForm').onsubmit=async e=>{e.preventDefault();if(!cart.length)return toast('Your bag is empty.');const button=e.submitter;button.disabled=true;button.textContent='Placing order…';try{const payment=$('cPayment')?.value||'cod';const customer={name:$('cName').value.trim(),phone:$('cPhone').value.trim(),email:$('cEmail').value.trim(),address:$('cAddress').value.trim(),city:$('cCity').value.trim(),state:$('cState').value.trim(),pincode:$('cPincode').value.trim()};let proof='';if(payment==='upi')proof=await uploadPaymentProof($('paymentScreenshot')?.files[0]);const order=await createOrder(customer,payment,proof);cart=[];save();$('checkoutForm').style.display='none';$('checkoutResult').innerHTML=`<div class="success"><span class="eyebrow">Order received</span><div class="order-number">${esc(order.orderNumber)}</div><p>${payment==='upi'?'Payment proof received and pending verification.':'Your COD order has been recorded successfully.'}</p><button class="hero-cta" onclick="location.reload()">Continue shopping</button></div>`;renderCart()}catch(err){console.error(err);toast(err.message||'Could not place the order.')}finally{button.disabled=false;button.textContent='Place order'}};
$('cartBtn').onclick=()=>{$('cartDrawer').classList.add('open');renderCart()};$('closeCart').onclick=()=>$('cartDrawer').classList.remove('open');$('closeCheckout').onclick=()=>$('checkoutModal').classList.remove('open');$('menuBtn').onclick=()=>document.body.classList.toggle('nav-open');$('searchBtn').onclick=()=>{const q=prompt('Search products by name, category, concern or ingredient');if(!q)return;const term=q.toLowerCase();const found=products.filter(p=>valuesFor(p).includes(term));renderProductList(found);document.querySelector('#shop')?.scrollIntoView({behavior:'smooth'})};document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{category=b.dataset.cat;document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x===b));renderProducts()});$('year').textContent=new Date().getFullYear();renderCartCount();renderAnnouncements();loadStore();loadProducts();