import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js';
import { getFirestore, collection, getDocs, addDoc, doc, getDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
import { getFunctions, httpsCallable } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-functions.js';
import { firebaseConfig } from './firebase-config.js';

const app=initializeApp(firebaseConfig),db=getFirestore(app),functions=getFunctions(app,'asia-south1');
const $=id=>document.getElementById(id); const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let products=[],cart=JSON.parse(localStorage.getItem('mirella-cart')||'[]'),category='all';
const save=()=>{localStorage.setItem('mirella-cart',JSON.stringify(cart));renderCartCount();};
const toast=m=>{const t=$('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)};
async function loadProducts(){try{const snap=await getDocs(collection(db,'products'));products=snap.docs.map(d=>({id:d.id,...d.data()})).filter(p=>p.active!==false);renderProducts()}catch(e){$('products').innerHTML='<div class="empty">The collection is temporarily unavailable. Please try again shortly.</div>';console.error(e)}}
function renderProducts(){const list=category==='all'?products:products.filter(p=>String(p.category||'').toLowerCase()===category);$('products').innerHTML=list.length?list.map(p=>`<article class="product"><div class="product-img">${p.imageUrl?`<img src="${esc(p.imageUrl)}" alt="${esc(p.name)}" loading="lazy">`:`<span>${esc(p.name||'Mirella')}</span>`}</div><div class="product-body"><span class="tag">${esc(p.category||'beauty')}</span><h3>${esc(p.name)}</h3><div class="desc">${esc(p.description||'A beautiful addition to your daily ritual.')}</div><div class="price-row"><strong>${money(p.price)}</strong><button class="add ${Number(p.stock||0)<=0?'sold':''}" data-add="${p.id}" ${Number(p.stock||0)<=0?'disabled':''}>${Number(p.stock||0)<=0?'—':'+'}</button></div></div></article>`).join(''):'<div class="empty">No products in this collection yet.</div>';document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addToCart(b.dataset.add));}
function addToCart(id){const p=products.find(x=>x.id===id);if(!p)return;const max=Math.max(0,Number(p.stock||0)),item=cart.find(x=>x.id===id);if(max<1)return toast('This product is currently out of stock.');if(item){if(item.qty>=max)return toast('You have reached the available stock.');item.qty++}else cart.push({id:p.id,name:p.name,price:Number(p.price||0),imageUrl:p.imageUrl||'',qty:1});save();toast('Added to your bag');}
function renderCartCount(){$('cartCount').textContent=cart.reduce((a,x)=>a+x.qty,0)}
function renderCart(){if(!cart.length){$('cartItems').innerHTML='<div class="empty">Your bag is waiting for something beautiful.</div>';$('cartSummary').innerHTML='';return}let total=0;$('cartItems').innerHTML=cart.map(x=>{total+=x.price*x.qty;return `<div class="cart-item"><div><b>${esc(x.name)}</b><div class="cart-meta">${money(x.price)} each</div></div><div class="qty"><button data-dec="${x.id}">−</button><span>${x.qty}</span><button data-inc="${x.id}">+</button></div></div>`}).join('');$('cartSummary').innerHTML=`<div class="total"><span>Total</span><span>${money(total)}</span></div><button class="btn primary" id="checkoutBtn" style="width:100%">Proceed to checkout</button>`;document.querySelectorAll('[data-inc]').forEach(b=>b.onclick=()=>changeQty(b.dataset.inc,1));document.querySelectorAll('[data-dec]').forEach(b=>b.onclick=()=>changeQty(b.dataset.dec,-1));$('checkoutBtn').onclick=()=>{$('cartDrawer').classList.remove('open');$('checkoutModal').classList.add('open')};}
function changeQty(id,delta){const i=cart.find(x=>x.id===id);if(!i)return;i.qty+=delta;if(i.qty<=0)cart=cart.filter(x=>x.id!==id);else{const p=products.find(x=>x.id===id);if(p&&i.qty>Number(p.stock||0))i.qty=Number(p.stock||0)}save();renderCart();}
function total(){return cart.reduce((a,x)=>a+x.price*x.qty,0)}
async function createOrder(customer,paymentMethod){const ref=`MG-${Date.now()}-${Math.random().toString(36).slice(2,7).toUpperCase()}`;const order={orderNumber:ref,customer,items:cart.map(x=>({productId:x.id,name:x.name,price:x.price,qty:x.qty,imageUrl:x.imageUrl||''})),subtotal:total(),shipping:total()>=999?0:99,total:total()+(total()>=999?0:99),status:'new',paymentStatus:paymentMethod==='cod'?'pending':'pending',paymentMethod,createdAt:serverTimestamp(),updatedAt:serverTimestamp()};const snap=await addDoc(collection(db,'orders'),order);return {id:snap.id,...order}}
async function startOnlinePayment(order){const call=httpsCallable(functions,'createRazorpayOrder');const r=await call({amount:Math.round(order.total*100),currency:'INR',receipt:order.orderNumber});const data=r.data;if(!window.Razorpay)await loadScript('https://checkout.razorpay.com/v1/checkout.js');return new Promise((resolve,reject)=>{const rz=new window.Razorpay({key:data.keyId,amount:data.amount,currency:data.currency,name:'Mirella Glow',description:'Beauty order',order_id:data.id,prefill:{name:order.customer.name,email:order.customer.email,contact:order.customer.phone},theme:{color:'#17110f'},handler:async response=>{try{const verify=httpsCallable(functions,'verifyRazorpayPayment');await verify({razorpayOrderId:response.razorpay_order_id,razorpayPaymentId:response.razorpay_payment_id,razorpaySignature:response.razorpay_signature,orderId:order.id});resolve(true)}catch(e){reject(e)}}});rz.on('payment.failed',()=>reject(new Error('Payment failed or was cancelled.')));rz.open()})}
function loadScript(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
$('checkoutForm').onsubmit=async e=>{e.preventDefault();if(!cart.length)return toast('Your bag is empty.');const button=e.submitter;button.disabled=true;button.textContent='Processing…';const customer={name:$('cName').value.trim(),phone:$('cPhone').value.trim(),email:$('cEmail').value.trim(),address:$('cAddress').value.trim(),city:$('cCity').value.trim(),state:$('cState').value.trim(),pincode:$('cPincode').value.trim()};const payment=$('cPayment').value;try{const order=await createOrder(customer,payment);if(payment==='online')await startOnlinePayment(order);cart=[];save();$('checkoutForm').style.display='none';$('checkoutResult').innerHTML=`<div class="success"><div class="eyebrow">Order confirmed</div><div class="order-number">${esc(order.orderNumber)}</div><p>Your order has been recorded successfully. We will contact you with updates.</p><button class="btn primary" onclick="location.reload()">Continue shopping</button></div>`;renderCart()}catch(err){console.error(err);toast(err.message||'Could not place the order. Please try again.')}finally{button.disabled=false;button.textContent='Place order'}};
$('cartBtn').onclick=()=>{$('cartDrawer').classList.add('open');renderCart()};$('closeCart').onclick=()=>$('cartDrawer').classList.remove('open');$('closeCheckout').onclick=()=>$('checkoutModal').classList.remove('open');$('menuBtn').onclick=()=>document.querySelector('.links').classList.toggle('mobile-open');$('searchBtn').onclick=()=>{const q=prompt('Search products');if(q){const found=products.filter(p=>String(p.name).toLowerCase().includes(q.toLowerCase()));$('products').innerHTML=found.length?found.map(p=>`<article class="product"><div class="product-img">${p.imageUrl?`<img src="${esc(p.imageUrl)}" alt="${esc(p.name)}">`:''}</div><div class="product-body"><span class="tag">${esc(p.category||'beauty')}</span><h3>${esc(p.name)}</h3><div class="desc">${esc(p.description||'')}</div><div class="price-row"><strong>${money(p.price)}</strong><button class="add" data-add="${p.id}">+</button></div></div></article>`).join(''):'<div class="empty">No matching products.</div>';document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>addToCart(b.dataset.add));}};
document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{category=b.dataset.cat;document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x===b));renderProducts()});$('year').textContent=new Date().getFullYear();$('whatsappLink').href='https://wa.me/?text='+encodeURIComponent('Hello Mirella Glow, I need help with an order.');renderCartCount();loadProducts();
