const STYLE_ID='mirella-slider-upgrade';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function injectStyles(){if(document.getElementById(STYLE_ID))return;const s=document.createElement('style');s.id=STYLE_ID;s.textContent=`
.mg-slider-wrap{position:relative}.mg-slider-rail{display:flex!important;grid-template-columns:none!important;gap:14px;overflow-x:auto;scroll-snap-type:x mandatory;scrollbar-width:none;padding:3px 3px 14px}.mg-slider-rail::-webkit-scrollbar{display:none}.mg-slider-rail>*{flex:0 0 min(310px,78vw);scroll-snap-align:start}.mg-slider-controls{display:flex;gap:8px;position:absolute;right:0;top:-62px}.mg-slider-btn{width:42px;height:42px;border:1px solid var(--line,#eaded8);background:rgba(255,255,255,.9);border-radius:50%;font-size:17px;color:var(--ink,#211a18);display:grid;place-items:center;cursor:pointer;transition:.2s}.mg-slider-btn:hover{background:var(--dark,#211816);color:#fff;border-color:var(--dark,#211816);transform:translateY(-1px)}#concernGrid .discovery-card,#resultGrid .discovery-card{min-height:170px;padding:24px;border-radius:2px;background:linear-gradient(145deg,#fff,#fbf2ee)}#concernGrid .discovery-card b,#resultGrid .discovery-card b{font-size:27px}#categories .category-grid{display:flex;gap:14px;overflow-x:auto;scroll-snap-type:x mandatory;scrollbar-width:none;padding:3px 2px 14px}#categories .category-grid::-webkit-scrollbar{display:none}#categories .category{flex:0 0 min(260px,62vw);scroll-snap-align:start;min-height:300px}#promotions .poster-track{scroll-behavior:smooth}#promotions .poster-card{flex-basis:min(72vw,720px);aspect-ratio:16/7.2}
@media(max-width:900px){.mg-slider-controls{position:static;margin:0 0 14px;justify-content:flex-end}.mg-slider-rail>*{flex-basis:min(340px,78vw)}}
@media(max-width:560px){.mg-slider-rail>*{flex-basis:82vw}.mg-slider-btn{width:38px;height:38px}.mg-slider-controls{margin-bottom:8px}#categories .category{flex-basis:76vw;min-height:270px}}
`;
document.head.appendChild(s)}
function controlsFor(rail){const wrap=rail.parentElement;if(!wrap)return;if(wrap.querySelector('.mg-slider-controls'))return;wrap.classList.add('mg-slider-wrap');const c=document.createElement('div');c.className='mg-slider-controls';c.innerHTML='<button class="mg-slider-btn" type="button" aria-label="Previous">‹</button><button class="mg-slider-btn" type="button" aria-label="Next">›</button>';const [prev,next]=c.children;prev.onclick=()=>rail.scrollBy({left:-rail.clientWidth*.82,behavior:'smooth'});next.onclick=()=>rail.scrollBy({left:rail.clientWidth*.82,behavior:'smooth'});wrap.insertBefore(c,rail)}
function enhanceRail(el){if(!el||el.dataset.mgSlider==='1')return;el.dataset.mgSlider='1';el.classList.add('mg-slider-rail');controlsFor(el)}
function enhanceDiscovery(){['concernGrid','resultGrid','ingredientGrid'].forEach(id=>{const el=document.getElementById(id);if(el)enhanceRail(el)})}
function enhanceCategories(){const el=document.querySelector('#categories .category-grid');if(el)enhanceRail(el)}
function enhancePosters(){const rail=document.getElementById('posterTrack');if(!rail||rail.dataset.mgControls==='1')return;rail.dataset.mgControls='1';controlsFor(rail)}
function injectPreviewLink(){if(document.getElementById('mgV2Link'))return;const footer=document.querySelector('.footer-links:last-child');if(!footer)return;const a=document.createElement('a');a.id='mgV2Link';a.href='storefront-v2.html';a.textContent='Preview new storefront';a.style.color='var(--accent,#a45e56)';footer.appendChild(a)}
function boot(){if(!document.getElementById('concernGrid'))return;injectStyles();enhanceDiscovery();enhanceCategories();enhancePosters();injectPreviewLink();const observer=new MutationObserver(()=>{enhanceDiscovery();enhanceCategories();enhancePosters();injectPreviewLink()});observer.observe(document.body,{childList:true,subtree:true});setTimeout(()=>observer.disconnect(),30000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
