import {getApps,getApp,initializeApp} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js';
import {getFirestore,collection,getDocs,doc,getDoc} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
import {firebaseConfig} from './firebase-config.js';
const app=getApps().length?getApp():initializeApp(firebaseConfig);const db=getFirestore(app);
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
let store={whatsapp:'',logoUrl:'',banners:[],videos:[],announcementSlides:[],homepageMedia:{}};let products=[];let cart=JSON.parse(localStorage.getItem('mirella-cart')||'[]');
const terms=p=>[p.name,p.category,p.description,p.badge,p.brand,p.concern,p.concerns,p.skinType,p.skinTypes,p.hairType,p.hairTypes,p.ingredients,p.ingredient,p.benefits,p.tags,p.result,p.results].flatMap(v=>Array.isArray(v)?v:[v]).join(' ').toLowerCase();
const has=(p,t)=>terms(p).includes(t.toLowerCase());
function toast(m){const t=$('toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
async function loadStore(){try{const s=await getDoc(doc(db,'settings','store'));if(s.exists())store={...store,...s.data()}}catch(e){console.error('Storefront V2 settings error',e)}applyMedia();renderAnnouncements();renderPosters();renderCategories();renderVideos();}
function applyMedia(){const m=store.homepageMedia||{};const hero=$('heroMedia');if(hero&&m.hero?.imageUrl)hero.style.backgroundImage=`url("${String(m.hero.imageUrl).replace(/"/g,'\\"')}")`;const story=$('storyMedia');if(story&&m.story?.imageUrl){story.style.backgroundImage=`url("${String(m.story.imageUrl).replace(/"/g,'\\"')}")`;const s=story.querySelector('strong');if(s)s.style.display='none'}const logo=$('logo');if(logo&&store.logoUrl){logo.src=store.logoUrl;logo.style.display='block';$('mark').style.display='none'}}
function renderAnnouncements(){const a=Array.isArray(store.announcementSlides)?store.announcementSlides.filter(Boolean):[];const list=a.length?a:['Beauty, curated beautifully','Free shipping on orders above ₹999','New drops · New rituals · New glow'];let i=0;const el=$('announcementText');el.textContent=typeof list[0]==='string'?list[0]:(list[0]?.text||'Mirella Glow');if(list.length>1)setInterval(()=>{i=(i+1)%list.length;el.textContent=typeof list[i]==='string'?list[i]:(list[i]?.text||'Mirella Glow')},3800)}
function renderPosters(){const el=$('posters');const list=(Array.isArray(store.banners)?store.banners:[]).filter(x=>x?.imageUrl);el.innerHTML=list.length?list.map(p=>`<article class="slide-card"><div class="poster"><img src="${esc(p.imageUrl)}" alt="${esc(p.title||'Mirella Glow promotion')}" loading="lazy"><div class="poster-copy"><small>${esc(p.eyebrow||'Mirella Glow')}</small><h3>${esc(p.title||'Beauty, refined.')}</h3>${p.subtitle?`<p>${esc(p.subtitle)}</p>`:''}</div></div></article>`).join(''):'<article class="slide-card"><div class="poster"><div class="poster-copy"><small>Mirella Glow</small><h3>Your campaigns appear here.</h3><p>Add posters in Media Studio and they will appear automatically.</p></div></div></article>';autoScroll(el,6500)}
function renderCategories(){const m=store.homepageMedia||{};const data=[['Skincare',m.category1?.imageUrl,'skin'],['Haircare',m.category2?.imageUrl,'hair'],['Bodycare',m.category3?.imageUrl,'body'],['Combos',m.category4?.imageUrl,'combos'],['Everything',m.category5?.imageUrl,'all']];$('categoriesRail').innerHTML=data.map(([name,url,cat])=>`<a class="slide-card category" href="#shop" data-category="${cat}">${url?`<img src="${esc(url)}" alt="${esc(name)}" loading="lazy">`:''}<b>${esc(name)}</b></a>`).join('');document.querySelectorAll('[data-category]').forEach(a=>a.onclick=e=>{e.preventDefault();const cat=a.dataset.category;renderProducts(cat==='all'?products:products.filter(p=>String(p.category||'').toLowerCase()===cat));location.hash='shop'})}
const concerns=['Acne & Breakouts','Pigmentation','Dark Spots','Dry Skin','Dehydration','Dullness','Sensitivity','Redness','Oil Control','Pores','Hair Fall','Frizz','Damage','Dandruff'];const results=['Glow','Hydration','Brightening','Barrier Care','Smooth Skin','Clear Skin','Hair Repair','Frizz Control','Scalp Care'];
function discoveryCard(label,t){const count=products.filter(p=>has(p,t)).length;return `<a class="slide-card discovery" href="#shop" data-term="${esc(t)}"><small>${label}</small><h3>${esc(t)}</h3><span>${count?count+' matching products':'Explore this edit'}</span></a>`}
function renderDiscovery(){const c=$('concernsRail'),r=$('resultsRail');c.innerHTML=concerns.map(x=>discoveryCard('Concern',x)).join('');r.innerHTML=results.map(x=>discoveryCard('Result',x)).join('');document.querySelectorAll('[data-term]').forEach(a=>a.onclick=e=>{e.preventDefault();renderProducts(products.filter(p=>has(p,a.dataset.term)));document.getElementById('shop').scrollIntoView({behavior:'smooth'})})}
function productCard(p){const stock=Number(p.stock||0);const compare=Number(p.compareAtPrice||p.comparePrice||0);const discount=compare>Number(p.price||0)?Math.round((1-Number(p.price||0)/compare)*100):0;return `<article class="product"><div class="product-media"><img src="${esc(p.imageUrl||'')}" alt="${esc(p.name)}" loading="lazy"><span class="badge">${stock?(esc(p.badge||'Curated')):'Sold out'}</span><button class="add" data-add="${esc(p.id)}" ${stock?'':'disabled'}>${stock?'Add to bag':'Sold out'}</button></div><a class="product-copy" href="product.html?id=${encodeURIComponent(p.id)}"><small>${esc(p.category||'Beauty')}</small><h3>${esc(p.name)}</h3><p>${esc(p.description||'A beautiful addition to your daily ritual.')}</p><div class="price"><strong>${money(p.price)}${compare>Number(p.price||0)?` <del style="font-size:10px;color:#a99">${money(compare)}</del>`:''}</strong><span>${discount?discount+'% off':stock?'In stock':'Unavailable'}</span></div></a></article>`}
function renderProducts(filter='all'){const list=filter==='all'?products:filter.length?filter:products;const el=$('products');el.innerHTML=list.length?list.slice(0,18).map(productCard).join(''):'<div style="padding:40px;color:var(--muted)">No matching products in this edit.</div>';document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(b.dataset.add));}
function add(id){const p=products.find(x=>x.id===id);if(!p||!Number(p.stock||0))return toast('This product is currently sold out.');const item=cart.find(x=>x.id===id);if(item)item.qty++;else cart.push({id,name:p.name,price:Number(p.price||0),qty:1});saveCart();toast('Added to your bag')}
function saveCart(){localStorage.setItem('mirella-cart',JSON.stringify(cart));$('count').textContent=cart.reduce((n,x)=>n+x.qty,0)}
function openBag(){const d=$('drawer');d.classList.add('open');const el=$('bagItems');let total=0;if(!cart.length){el.innerHTML='<p style="color:var(--muted);font-size:12px">Your bag is waiting for something beautiful.</p>'}else{el.innerHTML=cart.map(x=>{total+=x.price*x.qty;return `<div class="cart-row"><div><b>${esc(x.name)}</b><small>${money(x.price)} each</small></div><div class="qty"><button data-minus="${x.id}">−</button><span>${x.qty}</span><button data-plus="${x.id}">+</button></div></div>`}).join('')}$('bagTotal').textContent=money(total);const wa=String(store.whatsapp||'').replace(/\D/g,'');const msg=encodeURIComponent(`Hello Mirella Glow, I would like to order:\n${cart.map(x=>`${x.name} × ${x.qty}`).join('\n')}\nTotal: ${money(total)}`);$('whatsappOrder').href=wa?`https://wa.me/${wa}?text=${msg}`:'#';document.querySelectorAll('[data-minus]').forEach(b=>b.onclick=()=>change(b.dataset.minus,-1));document.querySelectorAll('[data-plus]').forEach(b=>b.onclick=()=>change(b.dataset.plus,1))}
function change(id,d){const x=cart.find(i=>i.id===id);if(!x)return;x.qty+=d;if(x.qty<1)cart=cart.filter(i=>i.id!==id);saveCart();openBag()}
function renderVideos(){const el=$('videos');const list=(Array.isArray(store.videos)?store.videos:[]).filter(v=>v?.videoUrl);el.innerHTML=list.length?list.map(v=>`<article class="slide-card video-card"><video src="${esc(v.videoUrl)}" ${v.posterUrl?`poster="${esc(v.posterUrl)}"`:''} muted autoplay loop playsinline preload="metadata"></video><div><small>${esc(v.tag||'Mirella Glow')}</small><h3>${esc(v.title||'Mirella moments')}</h3>${v.subtitle?`<p>${esc(v.subtitle)}</p>`:''}</div></article>`).join(''):'<article class="slide-card video-card"><div style="padding:35px"><small>Media Studio</small><h3>Your videos appear here.</h3><p>Add videos from the admin Media Studio.</p></div></article>';el.querySelectorAll('video').forEach(v=>{v.muted=true;v.play().catch(()=>{})})}
function autoScroll(el,ms){if(!el||el.children.length<2)return;let i=0;setInterval(()=>{i=(i+1)%el.children.length;el.scrollTo({left:el.children[i].offsetLeft,behavior:'smooth'})},ms)}
function bindArrows(){document.querySelectorAll('[data-target]').forEach(b=>b.onclick=()=>$(b.dataset.target)?.scrollBy({left:Number(b.dataset.dir)*($(b.dataset.target).clientWidth*.82),behavior:'smooth'}))}
async function loadProducts(){try{const s=await getDocs(collection(db,'products'));products=s.docs.map(d=>({id:d.id,...d.data()})).filter(p=>p.active!==false);renderDiscovery();renderProducts();}catch(e){console.error('Storefront V2 products error',e);$('products').innerHTML='<div style="padding:40px;color:#a64d45">The live catalog could not be loaded.</div>'}}
$('bagBtn').onclick=openBag;$('closeBag').onclick=()=>$('drawer').classList.remove('open');$('drawer').onclick=e=>{if(e.target===$('drawer'))$('drawer').classList.remove('open')};$('menuBtn').onclick=()=>toast('Use the navigation sections below to explore Mirella Glow.');bindArrows();saveCart();await loadStore();await loadProducts();
